
name: "Test Go Client"
on: ["push", "pull_request"]
jobs:
  test:
    runs-on: "ubuntu-latest"
    env:
      GOPATH: "${{ github.workspace }}"
      HZ_VERSION: "5.2"
    defaults:
      run:
        shell: "bash"
        working-directory: "$HOME/hazelcast-go-client-discovery"
    steps:
      - name: "Checkout Code"
        uses: "actions/checkout@v2"
        with:
          path: "$HOME/hazelcast-go-client-discovery"

      - name: "Setup Go"
        uses: "actions/setup-go@v2"
        with:
          go-version: "1.18"

      - name: "Install Go tools"
        run: |
          go install golang.org/x/tools/...@v0.1.11
          go install honnef.co/go/tools/cmd/staticcheck@2022.1.2

      - name: "Go mod tidy"
        run: |
          go mod tidy

      - name: "Run Checkers"
        run: |
          make check

      - name: "Run All Tests"
        run: |
          make test
